### ISSUE TITLE
FOD do SSC sync - ssc doesnt show details for the issues / the sync doesnt work

### ISSUE THREAD

**Issue by facilmovagit** [fortify/FortifySyncFoDToSSC#16]
### Current Behavior

I've used the fod to ssc sync tool with 2 fod projects.
1 of my company - the sync aparentlly works (the app is created on ssc) but the issue details are not displayed.
I've opened a support ticket with FOD and they upload the fpr of a test application to my FOD account.
After running the sync, the issues for this test app are shown on ssc's interface.
There are no erros and / or warnnings on the fod to ssc sync tool.

### Expected Behavior

show the details for the issues on the ssc interface

### Steps To Reproduce

![image1_app1-fod-page-with-issue-details](https://github.com/user-attachments/assets/cd7e8c9c-0aad-44ba-83df-f7961ea9989d)
![image2_app1-ssc-page-no-details-are-shown-for-the-issue](https://github.com/user-attachments/assets/6c4fb7fb-8c4f-4e06-ae1c-0a1f4b817b8c)
![image3_app1_app2_fod-to-ssc-sync-log](https://github.com/user-attachments/assets/7fe4630b-c364-4dc4-a87a-ae927f3567e7)
![image4_app2-ssc-page-with-details-for-the-issue](https://github.com/user-attachments/assets/9b3e8ff8-0b77-417f-be5b-3432786ef0ec)

### Environment

```markdown
OS: Ubuntu 24.04 LTS
SSC 24.2.0
FOD 24.3
FOD to SSC Sync 1.3.0
```

**Comment by rsenden** [comment]
Hi @facilmovagit, thanks for reporting this. 

Given the `Plist.info` file name for the issue for which details are not properly shown in SSC, I assume these are the scan results of a FoD Mobile scan (not Static or Dynamic scan), correct? Whereas the sample scan provided by the FoD team seems to be a Static scan.

The sync utility copies scan results by downloading the scan results from FoD in FPR file format, and uploading that FPR file to SSC. The problem is that mobile scans are a FoD-only feature; other Fortify tools like SSC and the FPR file format don't natively support such mobile scans (which are different from SAST scans of mobile application source code). 

To allow an FPR file for mobile scan results to be downloaded from FoD, FoD will represent these results in the FPR file as Dynamic scan results. This is clearly visible in SSC, with your two SSC screenshots showing a completely different issue layout and different engine type (`WEBINSPECT` for your mobile scan, `SCA` for the sample static scan provided by the FoD team).

So, from the perspective of the sync utility, everything is working as expected; download of the FPR file from FoD and upload to SSC completes without any errors, and there's nothing that we can do from the side of the sync utility to improve how mobile scan results are rendered in SSC. 

To take the sync utility out of the equation, I'd recommend you to manually reproduce this issue by downloading the FPR file for the mobile scan from the FoD portal and uploading this to a fresh SSC application version. You can then update your existing FoD ticket (or open a new ticket), stating that FPR files for mobile scan results downloaded from FoD are not properly rendered in SSC. 

I'll also notify the FoD product manager about this, but as this is more of an FoD/SSC compatibility issue rather than an issue with the FortifySyncFoDToSSC utility, it's better to handle this through an FoD ticket. Once you've confirmed that you can manually reproduce this behavior, we can close this issue and continue the discussed in the FoD ticket.

**Comment by facilmovagit** [comment]
Thank you for the prompt reply. 

Yes, it is a FoD Mobile scan.

> To take the sync utility out of the equation, I'd recommend you to manually reproduce this issue by downloading the FPR file for the mobile scan from the FoD portal and uploading this to a fresh SSC application version. You can then update your existing FoD ticket (or open a new ticket), stating that FPR files for mobile scan results downloaded from FoD are not properly rendered in SSC.

The issue has been reproduced taking the sync utility out of the equation.

I've created the test app on SSC and manually uploaded the FPR ( downloaded from FOD ). The issue details are not rendered on SSC. 

![image5_app_test_manual_fpr_upload_to_ssc](https://github.com/user-attachments/assets/5fd1d920-38d4-4d74-aed7-1f19a3bd690c)

> I'll also notify the FoD product manager about this, but as this is more of an FoD/SSC compatibility issue rather than an issue with the FortifySyncFoDToSSC utility, it's better to handle this through an FoD ticket. 

Thanks.


> Once you've confirmed that you can manually reproduce this behavior, we can close this issue and continue the discussed in the FoD ticket.

We can close it.
